// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://supiwygxypfqjzoqmlaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1cGl3eWd4eXBmcWp6b3FtbGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2NzI3ODUsImV4cCI6MjA4MjI0ODc4NX0.5dM_R53HJA3Q8YbBsqq7iDTiFxyQs33gtROnIJwfqAY";

// Import the client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: We intentionally create an untyped client here to avoid build-breaking
// type drift when the generated Database types don't match the live schema.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
